name: AppPipeline

pool:
  vmImage: 'ubuntu-latest'

trigger: none

resources:
  repositories:
  - repository: Scripts
    type: github
    name: skye1349/Scripts
    refs: refs/heads/main
    endpoints: skye1349

extends:
  template: MainPipeline.yaml