trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'


steps:
- script: echo "Starting Main Pipeline..."
  displayName: 'Initial Step'

- script: |
    echo "Simulating a task..."
    sleep 30  # Sleep for 30 seconds
  displayName: 'Simulated Task'

- script: |
    echo "This step will fail..."
    exit 1 # Deliberately fail the step
  displayName: 'failing step'

- script: |
    echo "This step is always doing no matter pipeline: canceled, failed, success, timeout"
  displayName: 'always test'
  condition: always()

# - task: TriggerBuild@3
#   inputs:
#     buildDefinition: 'TriggeredPipeline'
#     authenticationMethod: 'OAuth Token'
#     password: '$(System.AccessToken)'
#     waitForQueuedBuildsToFinish: true
#     waitForQueuedBuildsToFinishRefreshTime: '60'
#   condition: always()

    