trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
  - pipeline: FirstPipelineAlias
    source: MainPipeline
    trigger: 
      branches:
        include:
        - main
  - pipeline: SecondPipelineAlias
    source: SecondPipelineName
    trigger: 
      branches:
        include:
        - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Starting Triggered Pipeline..."
  displayName: 'Initial Step'