trigger: none

pool:
  vmImage: 'ubuntu-latest'

# resources:
#   pipelines:
#   - pipeline: MainPipeline
#     source: MainPipeline
#     trigger: 
#       branches:
#         include:
#         - main
  # - pipeline: SecondPipelineAlias
  #   source: SecondPipelineName
  #   trigger: 
  #     branches:
  #       include:
  #       - main


steps:
- script: echo "Starting Triggered Pipeline..."
  displayName: 'Initial Step'